compute_environment: LOCAL_MACHINE
deepspeed_config:
 deepspeed_config_file: /home/mila/s/shahrad.mohammadzadeh/projects/olmo_continual/scripts/configs/ppo_deepspeed_config.json
 zero3_init_flag: true
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 4
use_cpu: false